- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        cache_valid_time: 3600
        upgrade: dist
        autoremove: yes
      changed_when: False

  tasks:
    - include: tasks/os_family_check.yml
    - include: tasks/packages.yml
    - include: tasks/pips.yml
    - include: tasks/git.yml
