- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: 
        update_cache: yes
        #cache_valid_time: 3600
        autoremove: yes
    - name: upgrade repositories
      apt:
        name: "*" 
        state: latest
        force_apt_get: yes

  tasks:
    - include: tasks/os_family_check.yml
    - include: tasks/packages.yml
    - include: tasks/pips.yml
    - include: tasks/git.yml
