- name: Download Reconnoitre
  git:
    repo: https://github.com/codingo/Reconnoitre
    dest: /home/Reconnoitre
- name: Download SecLists 
  git:
    repo: https://github.com/danielmiessler/SecLists
    dest: /home/SecLists
- name: Download Responder
  git:
    repo: https://github.com/SpiderLabs/Responder
    dest: /home/Responder
