- name: Install packages
  ignore_errors: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - htop
    - nmap
    - netdiscover
    - tmux
    - gobuster
    - seclists
    - crackmapexec
