- name: Install packages
  ignore_errors: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:

    - htop
    - nmap
    - netdiscover
    - python3-pip
    - python-dev
    - libssl-dev
    - libffi-dev
    - tmux
    - gobuster
    - seclists
    - crackmapexec
