- name: Install pip packages
  ignore_errors: yes
  pip:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:

    - pip
    - virtualenv
    - docker
    - numpy
    - pandas
    - jupyterlab
